### ISSUE TITLE
Separate markdown files for different languages.

### ISSUE THREAD

**Issue by hturner** [thisisnic/first-contributions#43]
As discussed in 

- #41 

it might be easier to follow the instructions if each language is in a separate markdown file. This also opens the way for translation to more languages.

This could be implemented by making the README a landing page with links to separate markdowns for each language, maybe `first-contribution-en.md` and `first-contribution-es.md`.

**Comment by sdkdeepa** [comment]
Hello ! I would like to contribute on this. Please let me know.

**Comment by hturner** [comment]
Thanks for volunteering @sdkdeepa, however this was fixed in #45 by @minhducnguyen26, which I've just merged in.
