### ISSUE TITLE
can I translate readme to Arabic?

### ISSUE THREAD

**Issue by 0xGhada** [thisisnic/first-contributions#50]

**Comment by hturner** [comment]
@puregeek I just merged a PR which tidied up the translations, so it's in a good state to add a new translation to Arabic.

A few things to remember:
 - The image links of translations need prefixing with `../` as they are relative to a sub-directory (see other translations)
 - It would be great if you could translate the alt text too (it might be improved from the original English!)
 - Add a link to the README to the Arabic translation
 
 Looking forward to your contribution!

**Comment by 0xGhada** [comment]
@hturner Thank you very much for trusting me. I will translate it soon
